server:
  address: 0.0.0.0
  port: 8080

spring:
  application:
    name: stores

  datasource:
    url: jdbc:postgresql://localhost:5432/house_db?useUnicode=true&characterEncoding=UTF-8&stringtype=unspecified
    username: postgres
    password:

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

    properties:
      hibernate:
        connection:
          characterEncoding: UTF-8
          CharSet: UTF-8
          useUnicode: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
      format_sql: true

  web:
    resources:
      add-mappings: false

springdoc:
  api-docs:
    path: /v3/api-docs

  swagger-ui:
    path: /swagger-ui.html



